### ISSUE TITLE
Error with non common character

### ISSUE THREAD

**Issue by rodrigorega** [rubenhortas/pyPasswordsStats#1]
Traceback (most recent call last):
  File "pyPasswordsStats.py", line 165, in <module>
    len_dict)
  File "pyPasswordsStats.py", line 31, in __parse_file
    login.Print_info()
  File "C:\pyPasswordsStats\application\Login.py", line
 57, in Print_info
    print(("{0} {1}/{2}").format(tag, self.account, self.pwd))
  File "c:\Python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2122' in position
51: character maps to <undefined>

![image](https://cloud.githubusercontent.com/assets/3441785/9344257/94164d1a-4607-11e5-982d-42ae6b156a2a.png)

**Comment by rodrigorega** [comment]
If you want to test user input in depth: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt

**Comment by rubenhortas** [comment]
Would be solved.
